sudo: required
services:
  - docker

before_install:
  - docker build -t bebetaro/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bebetaro/react-test npm test

after_success:
  - docker build -t bebetaro/multi-client ./client
  - docker build -t bebetaro/multi-nginx ./nginx
  - docker build -t bebetaro/multi-server ./server
  - docker build -t bebetaro/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #Take those image and push them to docker hub
  - docker push bebetaro/multi-client
  - docker push bebetaro/multi-nginx
  - docker push bebetaro/multi-server
  - docker push bebetaro/multi-worker
